imgz/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("narnia/", admin.site.urls),
    path("narnia/", include("loginas.urls")),
    path("blog/", include("simpleblog.urls")),
    path("", include("main.urls")),
    path("auth/", include("tokenauth.urls", namespace="tokenauth")),
]

main/urls.py
"""The main application's URLs."""

from django.urls import path
from django.urls import re_path
from django.views.generic import TemplateView

from . import api
from . import views
from . import views_payment

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("account/", views.account, name="account"),
    path("upload/", views.image_upload, name="image-upload"),
    path("latest/", views.latest, name="latest"),
    path("logout", views.logout, name="logout"),
    re_path(r"^(?P<image_id>i[a-zA-Z0-9]{7})/$", views.image_page, name="image-page"),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})/delete/$",
        views.image_delete,
        name="image-delete",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})-(?P<size>\d+)\.(?P<extension>\w+)$",
        views.image_show_resized,
        name="image-show-resized",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})_(?P<size>\d+)\.(?P<extension>\w+)$",
        views.image_show_thumbnail,
        name="image-show-thumb",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})\.(?P<extension>\w+)$",
        views.image_show,
        name="image-show",
    ),
]

urlpatterns += [
    path("api/image/", api.ImageView.as_view(), name="api-image"),
    path("api/image/<image_id>/", api.ImageView.as_view(), name="api-image-detail"),
]

urlpatterns += [
    path("help/faq/", TemplateView.as_view(template_name="faq.html"), name="faq"),
    path("help/api/", views.api_docs, name="api-docs"),
    path("help/terms/", TemplateView.as_view(template_name="terms.html"), name="terms"),
]

urlpatterns += [
    path("money/", TemplateView.as_view(template_name="money.html"), name="money"),
    path(
        "money-safe/",
        TemplateView.as_view(template_name="money-safe.html"),
        name="money-safe",
    ),
    path("money/stripe/", views_payment.stripe_redirect, name="stripe-redirect"),
    path("money/stripe/webhook/", views_payment.stripe_webhook, name="stripe-webhook"),
    path("money/cryptocurrency/", views_payment.btc_redirect, name="btc-redirect"),
    path(
        "money/cryptocurrency/webhook/", views_payment.btc_webhook, name="btc-webhook"
    ),
    path(
        "money/thanks/",
        TemplateView.as_view(template_name="thanks.html"),
        name="payment-return",
    ),
]

simpleblog/urls.py
from django.urls import re_path

from .views import BlogDetailView
from .views import BlogListView
from .views import LatestEntriesFeed

urlpatterns = [
    re_path(
        r"^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$",
        BlogDetailView.as_view(),
        name="blog_detail",
    ),
    re_path(
        r"^archive/$",
        BlogListView.as_view(
            template_name="simpleblog/post_archive.html",
            page_template="simpleblog/post_archive_page.html",
        ),
        name="blog_archive",
    ),
    re_path(r"^latest/feed/$", LatestEntriesFeed()),
    re_path(r"^$", BlogListView.as_view(), name="blog_index"),
]

templates/fragments/image_card.html
<div class="col-6 col-md-3 col--image-list">
    <div class="card">
        <a href="{{ image.get_absolute_url  }}">
            <img src="{{ image.get_thumbnail_url }}" class="card-img-top" alt="{{ image.title }}" loading="lazy">
        </a>
        <div class="card-body">
            <a href="{{ image.get_absolute_url  }}">
                <h5 class="card-title">{{ image.title }}</h5>
            </a>
        </div>
        <div class="card-footer">
            <small class="text-muted">
                {{ image.uploaded }}

                <form
                    onsubmit="return confirm('Are you sure you want to delete this embarrassment of an image?');"
                    method="post"
                    action="{% url "main:image-delete" image.id %}"
                    >
                    <input type="submit" class="btn btn-danger btn-sm" style="margin-top: 5px" value="Delete">
                </form>
            </small>
        </div>
    </div>
</div>