imgz/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("narnia/", admin.site.urls),
    path("narnia/", include("loginas.urls")),
    path("blog/", include("simpleblog.urls")),
    path("", include("main.urls")),
    path("auth/", include("tokenauth.urls", namespace="tokenauth")),
]

main/urls.py
"""The main application's URLs."""

from django.urls import path
from django.urls import re_path
from django.views.generic import TemplateView

from . import api
from . import views
from . import views_payment

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("account/", views.account, name="account"),
    path("upload/", views.image_upload, name="image-upload"),
    path("latest/", views.latest, name="latest"),
    path("logout", views.logout, name="logout"),
    re_path(r"^(?P<image_id>i[a-zA-Z0-9]{7})/$", views.image_page, name="image-page"),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})/delete/$",
        views.image_delete,
        name="image-delete",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})-(?P<size>\d+)\.(?P<extension>\w+)$",
        views.image_show_resized,
        name="image-show-resized",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})_(?P<size>\d+)\.(?P<extension>\w+)$",
        views.image_show_thumbnail,
        name="image-show-thumb",
    ),
    re_path(
        r"^(?P<image_id>i[a-zA-Z0-9]{7})\.(?P<extension>\w+)$",
        views.image_show,
        name="image-show",
    ),
]

urlpatterns += [
    path("api/image/", api.ImageView.as_view(), name="api-image"),
    path("api/image/<image_id>/", api.ImageView.as_view(), name="api-image-detail"),
]

urlpatterns += [
    path("help/faq/", TemplateView.as_view(template_name="faq.html"), name="faq"),
    path("help/api/", views.api_docs, name="api-docs"),
    path("help/terms/", TemplateView.as_view(template_name="terms.html"), name="terms"),
]

urlpatterns += [
    path("money/", TemplateView.as_view(template_name="money.html"), name="money"),
    path(
        "money-safe/",
        TemplateView.as_view(template_name="money-safe.html"),
        name="money-safe",
    ),
    path("money/stripe/", views_payment.stripe_redirect, name="stripe-redirect"),
    path("money/stripe/webhook/", views_payment.stripe_webhook, name="stripe-webhook"),
    path("money/cryptocurrency/", views_payment.btc_redirect, name="btc-redirect"),
    path(
        "money/cryptocurrency/webhook/", views_payment.btc_webhook, name="btc-webhook"
    ),
    path(
        "money/thanks/",
        TemplateView.as_view(template_name="thanks.html"),
        name="payment-return",
    ),
]

simpleblog/urls.py
from django.urls import re_path

from .views import BlogDetailView
from .views import BlogListView
from .views import LatestEntriesFeed

urlpatterns = [
    re_path(
        r"^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$",
        BlogDetailView.as_view(),
        name="blog_detail",
    ),
    re_path(
        r"^archive/$",
        BlogListView.as_view(
            template_name="simpleblog/post_archive.html",
            page_template="simpleblog/post_archive_page.html",
        ),
        name="blog_archive",
    ),
    re_path(r"^latest/feed/$", LatestEntriesFeed()),
    re_path(r"^$", BlogListView.as_view(), name="blog_index"),
]

main/views.py
import datetime
from typing import Optional

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.http import require_POST
from loginas.utils import restore_original_login

from .models import Image
from .models import User
from .utils import process_upload
from .utils import resize_image
from .utils import UploadError


def get_image_response(image: bytes, format: str) -> HttpResponse:
    """Return an HttpResponse for a given image."""
    # We cast to bytes here because this is a memoryview on Postgres
    # but just bytes on SQLite.
    data = bytes(image)
    response = HttpResponse(data, content_type=f"image/{format}")
    response["Content-Length"] = len(data)
    return response


def get_image(image_id: str) -> Image:
    image = get_object_or_404(Image, pk=image_id)
    return image


def delete_all_their_shit(user: User) -> None:
    """
    Delete all the user's shit.
    """
    for image in Image.objects.filter(user=user):
        image.delete()

    user.upgraded_until = datetime.date(2000, 1, 1)
    user.storage_space = 0
    user.bonus_space = 0
    user.save()


@login_required
def logout(request):
    """
    Log the user out.

    This is a custom logout view that restores the original user with django-loginas.
    """
    restore_original_login(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


@login_required
def account(request):
    if request.method == "POST":
        if request.GET.get("delete") == "allmyshit":
            delete_all_their_shit(request.user)
            messages.success(request, "Good riddance.")
            logout(request)
        elif request.GET.get("unsub") == "scribeme":
            request.user.stop_stripe_subscription()
            messages.success(
                request, "Okay your subscription has been canceled. I think."
            )
        return redirect("main:index")

    return render(request, "account.html")


def api_docs(request: HttpRequest) -> HttpResponse:
    api_key = request.user.api_key if request.user.is_authenticated else "y0uRAP1k3y"
    return render(request, "api.html", {"api_key": api_key})


def latest(request: HttpRequest) -> HttpResponse:
    if not request.user.is_superuser:
        raise Http404()
    try:
        items = int(request.GET.get("items", ""))
    except Exception:
        items = 100

    return render(
        request,
        "latest.html",
        {
            "images": Image.objects.defer("data", "thumbnail_512").order_by(
                "-uploaded"
            )[:items]
        },
    )


def index(request: HttpRequest) -> HttpResponse:
    if not request.user.is_authenticated:
        if request.GET.get("v") == "s":
            return render(request, "simple_landing.html")
        elif request.GET.get("v") == "c":
            return render(request, "complex_landing.html")
        else:
            return render(request, "index.html")

    if not request.user.is_upgraded:
        return render(request, "unpaid.html")

    return render(
        request,
        "home.html",
        {
            "images": request.user.images.defer("data", "thumbnail_512").order_by(
                "-uploaded"
            )
        },
    )


def image_show_resized(
    request: HttpRequest, image_id: str, size: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show a resized image.
    """
    image = get_image(image_id)
    s = int(size)
    if s != 1280:
        return HttpResponseNotFound("Size not found.")

    data = resize_image(image.data, s)
    return get_image_response(data, image.format)


def image_show_thumbnail(
    request: HttpRequest, image_id: str, size: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show an image's thumbnail.
    """
    image = get_image(image_id)
    s = int(size)
    if s != 512:
        return HttpResponseNotFound("Thumbnail not found.")

    return get_image_response(image.thumbnail_512, image.format)


def image_page(
    request: HttpRequest, image_id: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show an image page.
    """
    image = get_image(image_id)

    if request.method == "POST":
        if image.user != request.user:
            messages.error(request, "No.")
            return redirect(image)

        try:
            image.set_title(request.POST.get("title"))
        except ValueError as e:
            messages.error(request, str(e))
            return redirect(image)

        image.save()
        messages.success(
            request, "The previous title sucked, huh? Well this one isn't any better."
        )
        return redirect(image)

    image.increment_views()
    return render(
        request, "image.html", {"image": image, "nopreview": request.GET.get("np")}
    )


def image_show(
    request: HttpRequest, image_id: str, extension: Optional[str] = None
) -> HttpResponse:
    """
    Show a bare image.
    """
    image = get_image(image_id)
    return get_image_response(image.data, image.format)


@login_required  # type: ignore
@require_POST  # type: ignore
def image_delete(
    request: HttpRequest, image_id: str, extension: Optional[str] = None
) -> HttpResponse:
    image = get_image(image_id)
    if image.user != request.user and not request.user.is_superuser:
        raise Http404
    image.delete()
    messages.success(request, "Okay, the image is gone. It was a dick pic, wasn't it?")
    return redirect("main:index")


@login_required  # type: ignore
def image_upload(request: HttpRequest) -> HttpResponse:
    class ImageUploadForm(forms.Form):
        EXPIRATION = [
            [10, "ten minutes"],
            [60, "an hour"],
            [24 * 60, "a day"],
            [7 * 24 * 60, "a week"],
            [14 * 24 * 60, "two weeks"],
            [30 * 24 * 60, "a month"],
            [None, "never"],
        ]

        title = forms.CharField(
            max_length=200, help_text="The title of the image.", required=False
        )
        expires = forms.ChoiceField(
            choices=EXPIRATION, initial=None, label="Expires in", required=False
        )

        image = forms.FileField()

    if request.method == "POST":
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                image = process_upload(
                    request.FILES,
                    request.user,
                    title=form.cleaned_data["title"],
                    expires_in=int(form.cleaned_data["expires"])
                    if form.cleaned_data["expires"]
                    else None,
                )
            except UploadError as e:
                messages.error(request, str(e))
                return redirect("main:image-upload")
            else:
                return redirect(image)
    else:
        form = ImageUploadForm()
    return render(request, "upload.html", {"form": form})

templates/analytics.html
{% if not settings.DEBUG %}
<noscript><img src="https://nsa.stavros.io/ingress/de5a9062-c300-4065-88c9-14e5cf1c182b/pixel.gif"></noscript>
<script src="https://nsa.stavros.io/ingress/de5a9062-c300-4065-88c9-14e5cf1c182b/script.js"></script>
{% endif %}

templates/api.html
{% extends "base.html" %}

{% load human_size %}

{% block title %}API documentation{% endblock %}
{% block ogtitle %}API documentation{% endblock %}

{% block content %}
  	<!--begin services section -->
    <section class="section-grey section-top-border" id="features">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-8-->
                <div class="col-md-8 offset-md-2 text-center padding-bottom-10 left-text">
                    <h3>API documentation</h3>

                    <p>
                    Ugh, I didn't want to go into all this detail, but it's not like anyone is going to look at the
                    publicly-available, amply-documented, simple code to figure out how the API works, so here we are.
                    </p>

                    <p>
                    The API is pretty RESTful and non-surprising, you authenticate with your API key and it's all good.
                    </p>


                    <h4>Authentication</h4>

                    <p>
                    Authentication is easy enough that even you can do it. Just use your API key as your password in
                    HTTP Basic auth.
                    </p>


                    <h4>Uploading an image</h4>

                    <p>
                    To upload an image, simply <code>POST</code> to
                    <code>https://{{ request.site.domain }}{% url "main:api-image" %}</code> as a
                    <code>multipart/form-data</code> content type, with your image in the <code>image</code> field and
                    the title in the <code>title</code> field.<br>
                    You can also set the <code>expires_in</code> field to the number of minutes you want the image to
                    expire in.
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image" %} \<br>
                            &nbsp;&nbsp;&nbsp;-F "image=@/some/image/path.png" \<br>
                            &nbsp;&nbsp;&nbsp;-F "title=I am alone."
                    </code>
                    </p>


                    <h4>Retrieving an image</h4>

                    <p>
                    This doesn't even need auth. Just make a <code>GET</code> request to
                    <code>https://{{ request.site.domain }}{% url "main:api-image-detail" "image_id" %}</code>
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl https://{{ request.site.domain }}{% url "main:api-image-detail" "iJKuc6HA" %}
                    </code>
                    </p>

                    <h4>Editing an image</h4>

                    <p>
                    To edit an image, <code>PUT</code> to
                    <code>https://{{ request.site.domain }}{% url "main:api-image-detail" "image_id" %}</code>.
                    You can currently only change the title by passing the <code>title</code> field. The request should
                    be JSON-encoded with the appropriate content type.
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image-detail" "iJKuc6HA" %} \<br>
                        &nbsp;&nbsp;&nbsp;-H 'Content-Type: application/json' -X PUT -d '{"title": "This is me."}'
                    </code>
                    </p>

                    <h4>Deleting an image</h4>

                    <p>
                    Unsurprisingly, <code>DELETE</code> to
                    <code>https://{{ request.site.domain }}{% url "main:api-image-detail" "image_id" %}</code>.
                    </p>

                    <p>
                    Example:
                    </p>

                    <p>
                    <code>
                        curl -X DELETE https://:{{ api_key }}@{{ request.site.domain }}{% url "main:api-image-detail" "iJKuc6HA" %}
                    </code>
                    </p>
                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end services section -->
{% endblock %}

templates/base.html
{% load i18n static %}<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <title>{% block title %}Image sharing. No bullshit.{% endblock %} - {{ request.site.name }}</title>

    <!-- Loading Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dosis:500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,700" rel="stylesheet">

    <!-- favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "images/icons/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" href="{% static "images/icons/favicon-32x32.png" %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static "images/icons/favicon-16x16.png" %}" sizes="16x16">
    <link rel="manifest" href="{% static "images/icons/site.webmanifest" %}">
    <link rel="mask-icon" href="{% static "images/icons/safari-pinned-tab.svg" %}" color="#33759F">
    <link rel="shortcut icon" href="{% static "images/icons/favicon.ico" %}">
    <meta name="monetization" content="$ilp.uphold.com/rzfPBEBJPRaZ">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="{% static "images/icons/browserconfig.xml" %}">
    <meta name="theme-color" content="#ffffff">

    {% if image and not nopreview %}
    <link rel="canonical" href="https://{{ request.site.domain }}{{ image.get_absolute_url }}" />

    <meta property="og:title" content="{{ image.title }}">
    <meta property="og:site_name" content="{{ request.site.name }}">
    <meta property="og:url" content="https://{{ request.site.domain }}{{ image.get_absolute_url }}">
    <meta property="og:description" content="A sublime image, viewed {{ image.views }} times.">
    <meta property="og:type" content="object">
    <meta property="og:image" content="https://{{ request.site.domain }}{{ image.get_thumbnail_url }}">
    <meta property="og:image:width" content="512">
    <meta property="og:image:height" content="512">
    {% else %}
    <meta property="og:title" content="{% block ogtitle %}Image sharing. No bullshit.{% endblock %} - {{ request.site.name }}">
    <meta property="og:site_name" content="{{ request.site.name }}">
    <meta property="og:url" content="https://{{ request.site.domain }}">
    <meta property="og:description" content="{{ request.site.name}} shares images.">
    <meta property="og:type" content="object">
    <meta property="og:image" content="https://{{ request.site.domain }}{% static "images/icons/android-chrome-512x512.png" %}">
    <meta property="og:image:width" content="512">
    <meta property="og:image:height" content="512">
    {% endif %}

    <script>
        window.addEventListener('DOMContentLoaded', (event) => {
            [...document.querySelectorAll('[data-toggle]')].forEach((toggler) => {
                toggler.addEventListener('click', function(e) {
                    document.querySelector(this.dataset.target).classList.toggle('show');
                });
            });
        });
    </script>
    {% block head %}
    {% endblock %}
</head>

<body class="{% block page-class %}{% endblock %}">
    <!--begin header -->
    <header class="header">

        <!--begin navbar-fixed-top -->
        <nav class="navbar navbar-default navbar-fixed-top">

            <!--begin container -->
            <div class="container">

                <!--begin navbar -->
                <nav class="navbar navbar-expand-lg">

                    <!--begin logo -->
                    <a class="navbar-brand" href="/"><img src="{% static "images/logo.png" %}"/> {{ request.site.name }}</a>
                    <!--end logo -->

                    <!--begin navbar-toggler -->
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
                    </button>
                    <!--end navbar-toggler -->

                    <!--begin navbar-collapse -->
                    <div class="navbar-collapse collapse" id="navbarCollapse" style="">

                        <!--begin navbar-nav -->
                        <ul class="navbar-nav ml-auto">

                            {% if request.user.is_authenticated %}
                            <li><a href="{% url "main:faq" %}">FAQ</a></li>
                            <li><a href="/blog/">Blog</a></li>
                            {% if not user.is_paying %}
                            <li><a href="{% url "main:money" %}">Pricing</a></li>
                            {% endif %}
                            <li><a href="{% url "main:image-upload" %}">Upload</a></li>
                            <li><a href="{% url "main:account" %}">Account</a></li>
                            <li><a href="{% url "main:logout" %}">Log out</a></li>
                            {% else %}
                            <li><a href="/blog/">Blog</a></li>
                            <li><a href="{% url "main:faq" %}">FAQ</a></li>
                            <li><a href="{% url "main:money" %}">Pricing</a></li>
                            <li class="discover-link"><a href="/#login" class="external discover-btn">Log in</a></li>
                            {% endif %}

                        </ul>
                        <!--end navbar-nav -->

                    </div>
                    <!--end navbar-collapse -->

                </nav>
                <!--end navbar -->

            </div>
    		<!--end container -->

        </nav>
    	<!--end navbar-fixed-top -->

    </header>
    <!--end header -->

    <div class="stupid-separator"></div>

    {% if messages %}
    <section class="section-white" style="padding: 20px 0 0px 0">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="benefits">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><i class="fa fa-circle-notch"></i> {{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    </section>
    {% endif %}

{% block content %}
{% endblock %}

    <!--begin footer -->
    <div class="footer">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12 -->
                <div class="col-md-12 text-center">

                    <p>
                    Made by <a href="https://www.stavros.io" target="new">Stavros</a>
                    |
                    <a href="{% url "main:api-docs" %}">API</a>
                    |
                    <a href="{% url "main:terms" %}">Terms and conditions</a>
                    </p>

                    <ul class="footer_contact">
                        <li><a href="mailto:hi@stavros.io?subject={{ request.site.name }}+questions"><i class="fas fa-envelope"></i></a></li>
                        <li><a href="https://twitter.com/stavros"><i class="fab fa-twitter"></i></a></li>
                    </ul>

                </div>
                <!--end col-md-6 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </div>

{% include "analytics.html" %}
</body>
</html>

templates/unpaid.html
{% extends "base.html" %}

{% load humanize %}

{% block title %}What now?{% endblock %}
{% block ogtitle %}What now?{% endblock %}

{% block content %}
    <!--begin newsletter section -->
    <section class="section-blue" id="login">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12 -->
                <div class="col-md-12 text-center padding-top-50 padding-bottom-20">

                    <h3 class="white-text">Congratulations, your trial expired.</h3>
                    <p class="white-text">There's nothing you can do here.</p>

                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end newsletter section -->

  	<!--begin services section -->
    <section class="section-grey section-top-border" id="features">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12-->
                <div class="col-md-8 offset-md-2 text-center padding-bottom-10">

                    <h2 class="section-title">Okay listen.</h2>

                    <p class="section-subtitle text-left">
                    Your {{ request.site.name }} trial has expired. It's time for you to take out your wallet and
                    <a href="{% url "main:money" %}">pay for what you use</a> like a normal, non-cheap person.
                    </p>

                    <p class="section-subtitle text-left">
                    Head over to the <a href="{% url "main:money" %}">money page</a> and give me yours. Then I will
                    release your images. If you fail to do this, your images may get deleted soon to make room for
                    people who aren't cheapskates.
                    </p>

                    <p class="section-subtitle text-left">
                    Go back to Facebook or some other "free" website.
                    </p>
                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end services section -->
{% endblock %}

templates/upload.html
{% extends "base.html" %}

{% load human_size %}

{% block head %}
<script>
window.onload = function () {
    var isAdvancedUpload = function () {
        var div = document.createElement('div');
        return (('draggable' in div) || ('ondragstart' in div && 'ondrop' in div)) && 'FormData' in window && 'FileReader' in window;
    }();

    if (isAdvancedUpload)
    {
        var form = document.getElementById("drag-drop");
        var input = form.querySelector('input[type="file"]');
        var label = form.querySelector('label[for="id_image"]');

        // Block label from doing anything while clicked. Previously, in
        // Chrome (including Android) this caused a file chooser to be opened
        // twice; once when the label was clicked, and once when the event
        // propagated up to the parent `#drag-drop`.
        label.style.pointerEvents = 'none';

        document.getElementById("id_image").addEventListener('change', function(e) {
            document.getElementById("upload_form").querySelector(".drag-files-label").innerHTML = e.target.files[0].name;
        });

        ['drag', 'dragstart', 'dragend', 'dragover', 'dragenter', 'dragleave', 'drop'].forEach(function (event) {
            form.addEventListener(event, function (e) {
                e.preventDefault();
                e.stopPropagation();
            });
        });

        ['dragover', 'dragenter'].forEach(function (event) {
            form.addEventListener(event, function () {
                form.classList.add('dragover');
            });
        });

        ['dragleave', 'dragend', 'drop'].forEach(function (event) {
            form.addEventListener(event, function () {
                form.classList.remove('dragover');
            });
        });

        document.getElementById("drag-drop").addEventListener('click', function (e) {
            document.getElementById("id_image").click(e);
        });

        form.addEventListener('drop', function (e) {
            var droppedFiles = e.dataTransfer.files; // the files that were dropped

            if (droppedFiles.length == 1)
            {
                document.getElementById("id_image").files = droppedFiles;
                form.querySelector(".drag-files-label").innerHTML = droppedFiles[0].name;
            } else {
                alert("What do you think you're doing? You can only upload a single file.");
            }
        });
    }
};
</script>
{% endblock %}

{% block title %}Upload an image{% endblock %}
{% block ogtitle %}Upload an image{% endblock %}

{% block content %}
  	<!--begin services section -->
    <section class="section-grey section-top-border" id="features">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12-->
                <div class="col-md-8 offset-md-2 text-center padding-bottom-10">
                    <h3>Upload an image</h3>

                    {% if request.user.is_upgraded %}
                    <p>
                    You can upload an image using this shitty form:
                    </p>



                    <p>
                    <form id="upload_form" method="post" enctype="multipart/form-data" action="{% url "main:image-upload" %}">
                        {{ form.non_field_errors }}

                        <div id="drag-drop" class="drag-drop">
                            <label class="drag-files-label" for="{{ form.image.id_for_label }}">
                                Drop your file here or click to select
                            </label>
                            <div class="col-sm-10">
                                <input type="file" accept="image/*" class="form-control-file" name="image" required id="id_image">
                            </div>
                        </div>

                        <div class="form-group row">
                            {{ form.title.errors }}
                            <label class="col-sm-2 col-form-label" for="{{ form.title.id_for_label }}">Image title</label>
                                <div class="col-sm-10">
                                    <input type="text" name="title" class="form-control" maxlength="200"
                                    id="id_title" placeholder="My amazing title, such prose">
                                </div>
                        </div>


                        <div class="form-group row">
                            {{ form.expires.errors }}
                            <label class="col-sm-2 col-form-label" for="{{ form.expires.id_for_label }}">Expires in</label>
                            <div class="col-sm-10">
                                <select name="expires" id="id_expires" style="width: 100%">
                                    <option value="10">ten minutes</option>
                                    <option value="60">an hour</option>
                                    <option value="1440">a day</option>
                                    <option value="10080">a week</option>
                                    <option value="20160">two weeks</option>
                                    <option value="43200">a month</option>
                                    <option value="" selected="">never</option>
                                </select>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-blue small scrool">Upload!</button>
                    </form>
                    </p>
                    {% else %}
                    <p>
                    You can't do anything until you pay! Go back.
                    </p>
                    {% endif %}
                </div>
                <!--end col-md-12 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>
    <!--end services section -->
{% endblock %}